In [2]:
# toy model

import torch
from torch import nn

model = nn.Linear(10, 1)

# import Lion and instantiate with parameters

from lion_pytorch import Lion

opt = Lion(model.parameters(), lr=1e-4, weight_decay=1e-2)

# forward and backwards

loss = model(torch.randn(10))
loss.backward()

# optimizer step

opt.step()
opt.zero_grad()

In [3]:
loss

tensor([1.0338], grad_fn=<AddBackward0>)

In [11]:
import sys

In [ ]:
sys.pa

In [12]:
sys.path.append('C:/Users/wun2/github/reaction_rl/REACTRL/image_modules/automl/efficientnetv2')

In [7]:
from REACTRL.image_modules.automl.efficientnetv2 import *

In [17]:
import effnetv2_model 

In [18]:
model = effnetv2_model.EffNetV2Model('efficientnetv2-s')

In [24]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 stem (Stem)                 (None, 112, 112, 24)      744       
                                                                 
 blocks_0 (FusedMBConvBlock)  (None, 112, 112, 24)     5280      
                                                                 
 blocks_1 (FusedMBConvBlock)  (None, 112, 112, 24)     5280      
                                                                 
 blocks_2 (FusedMBConvBlock)  (None, 56, 56, 48)       25920     
                                                                 
 blocks_3 (FusedMBConvBlock)  (None, 56, 56, 48)       93120     
                                                                 
 blocks_4 (FusedMBConvBlock)  (None, 56, 56, 48)       93120 

In [28]:
import preprocessing
import cv2


In [43]:
image = tf.io.read_file('sharpened_image.jpg')

In [39]:
image

<tf.Tensor: shape=(), dtype=string, numpy=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x00y\x00\xb3\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x

In [40]:
image = cv2.imread('sharpened_image.jpg')

In [58]:
tf.repeat(image, 3, axis=0)

<tf.Tensor: shape=(384, 128, 3), dtype=float32, numpy=
array([[[ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        ...,
        [ 0.9003906 ,  0.5332031 , -0.8261719 ],
        [ 0.9091797 ,  0.5419922 , -0.8173828 ],
        [ 0.9140625 ,  0.546875  , -0.8125    ]],

       [[ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        ...,
        [ 0.9003906 ,  0.5332031 , -0.8261719 ],
        [ 0.9091797 ,  0.5419922 , -0.8173828 ],
        [ 0.9140625 ,  0.546875  , -0.8125    ]],

       [[ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        [ 0.875     ,  0.578125  , -0.8828125 ],
        ...,
        [ 0.9003906 ,  0.5332031 , -0.8261719 ],
        [ 0.9091797 ,  0.5419922 , -0.8173828 ],
        [ 0.9140625 ,  0.546875  , -0.8125    ]],

       ...,

     

In [55]:
tf.expand_dims(image, 0)

<tf.Tensor: shape=(1, 128, 128, 3), dtype=float32, numpy=
array([[[[ 0.875     ,  0.578125  , -0.8828125 ],
         [ 0.875     ,  0.578125  , -0.8828125 ],
         [ 0.875     ,  0.578125  , -0.8828125 ],
         ...,
         [ 0.9003906 ,  0.5332031 , -0.8261719 ],
         [ 0.9091797 ,  0.5419922 , -0.8173828 ],
         [ 0.9140625 ,  0.546875  , -0.8125    ]],

        [[ 0.8847656 ,  0.5878906 , -0.8828125 ],
         [ 0.8847656 ,  0.5878906 , -0.876709  ],
         [ 0.8847656 ,  0.5878906 , -0.876709  ],
         ...,
         [ 0.8881836 ,  0.5209961 , -0.8383789 ],
         [ 0.90063477,  0.53344727, -0.82592773],
         [ 0.9238281 ,  0.5566406 , -0.8027344 ]],

        [[ 0.8876953 ,  0.59375   , -0.89160156],
         [ 0.88586426,  0.5900879 , -0.883667  ],
         [ 0.8847656 ,  0.58898926, -0.8847656 ],
         ...,
         [ 0.8951416 ,  0.5279541 , -0.8372803 ],
         [ 0.9042969 ,  0.5371094 , -0.82592773],
         [ 0.9238281 ,  0.5566406 , -0.8027344

In [44]:
image = preprocessing.preprocess_image(
    image, 128, is_training=False)

In [59]:
logits = model(tf.repeat(tf.expand_dims(image, 0), 5, axis=0), False)

In [60]:
logits

<tf.Tensor: shape=(5, 1000), dtype=float32, numpy=
array([[-0.00477067, -0.02119965, -0.00586628, ..., -0.02349844,
         0.01018593, -0.0126137 ],
       [-0.00477067, -0.02119965, -0.00586628, ..., -0.02349844,
         0.01018593, -0.0126137 ],
       [-0.00477067, -0.02119965, -0.00586628, ..., -0.02349844,
         0.01018593, -0.0126137 ],
       [-0.00477067, -0.02119965, -0.00586628, ..., -0.02349844,
         0.01018593, -0.0126137 ],
       [-0.00477067, -0.02119966, -0.00586628, ..., -0.02349844,
         0.01018592, -0.01261369]], dtype=float32)>

In [61]:
pred = tf.keras.layers.Softmax()(logits)
idx = tf.argsort(logits[0])[::-1][:5].numpy()

In [62]:
idx

array([115, 847, 728, 935, 530])

In [52]:
import ast
classes = ast.literal_eval(open(labels_map, "r").read())

NameError: name 'labels_map' is not defined